# Generated by Django 5.2.7 on 2025-10-23 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='usuarios_registrados',
            field=models.ManyToManyField(related_name='eventos_registrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
