# Generated by Django 5.2.7 on 2025-10-23 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_eventos_usuarios_registrados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='usuarios_registrados',
            field=models.ManyToManyField(related_name='lista_eventos', to=settings.AUTH_USER_MODEL),
        ),
    ]
